### PR TITLE
Issue 1571 - Options group strings and limits

### PR DESCRIPTION
**Pull request by hssm**
[Issue 1571](http://code.google.com/p/ankidroid/issues/detail?id=1571)
- Updated some strings to match the desktop client.
- Fixed an option using the wrong units 
- Added limits to the input text length.
- Disabled the add/remove options group item for now since it doesn't do anything yet.

The desktop client also has minimum and maximum values for most of these which we aren't checking for. I'll do that next.

### CODE REVIEW

**Comment by hssm** [comment]
I've added another commit that does validation on the input. This fixes [Issue1578](http://code.google.com/p/ankidroid/issues/detail?id=1578) and ensures input is kept within the acceptable range for the respective field. I copied the limits from dconf.ui. Entering a blank value will reuse the value that was already set.

I also changed the stepping regular expressions to use + instead of \* since they were crashing on empty input.

There are still a couple of bugs around this which I'll open new issues for since I don't know how to fix them myself (they existed before these commits).

**Comment by flerda** [comment]
Could you also rebase this change? Thanks!

**Comment by hssm** [comment]
Sorry for the wait, I had to make some more changes.

I've rebased, fixed the limit we discussed, and added validation to the steps fields which were not validated before. It turns out you can have decimals as steps as well (e.g., 0.5 minutes). Found [an issue](http://code.google.com/p/ankidroid/issues/detail?id=1662) already open for that. Decimals are going to suffer from [this issue](http://code.google.com/p/ankidroid/issues/detail?id=1675), however, for anything that isn't x.5. Hopefully that's fixable.

There is another issue remaining that I haven't figured out how to fix yet. I'd be grateful for some pointers. Currently, the values in the input dialogs are cached. So if you enter some invalid input, like "asdf" in steps, you will get a warning and the value is discarded. If you open the dialog again, it still says "asdf" instead of the currently set value. It does this for all input dialogs in the deck options. What is the right way to set the value in the dialog before it's shown?

**Comment by flerda** [comment]
Let's merge this for now and fix the other issues separately.

**Pull request merged**
