### PR TITLE
Issue 1248 - fix for delete dialog

### PR DESCRIPTION
**Pull request by hssm**
This fixes one of the steps described in Issue 1248 where repeated attempts at deleting decks will always display the name of the first one in the confirmation dialog. The problem was that it never got a chance to build the dialog properly since it quit if the collection was open (which doesn't make sense).

### CODE REVIEW

**Comment by hssm** [comment]
A new bug report ([Issue 1554](http://code.google.com/p/ankidroid/issues/detail?id=1554)) came in with this exact problem, and there's a different fix on there already.

**Comment by flerda** [comment]
Thanks for spotting that.
I asked the person who fixed it to send me a pull request.
We can probably close this one.

**Comment by flerda** [comment]
We will keep this version of the fix, because the other missed one case that this one is actually already taking care of.
Please have a look at my comment above.

**Comment by hssm** [comment]
Sorry, I messed this up. I did a git pull before making the changes. I don't know how to clean this up anymore.

**Comment by hssm** [comment]
I'm closing this pull request and opening a new one. I'm pretty sure I fubar'd this branch.

**Pull request closed without merging**
